const navButtons=document.querySelectorAll("[data-tab]"),tabSections=document.querySelectorAll(".tab-section");
function openTab(id){tabSections.forEach(s=>s.classList.remove("active"));navButtons.forEach(b=>b.classList.remove("active"));const s=document.getElementById(id);if(s)s.classList.add("active");document.querySelectorAll(`[data-tab="${id}"]`).forEach(b=>b.classList.add("active"));document.getElementById("navigation").classList.remove("open");window.scrollTo({top:0,behavior:"smooth"})}
navButtons.forEach(b=>b.addEventListener("click",()=>openTab(b.dataset.tab)));
document.querySelectorAll("[data-scroll-tab]").forEach(b=>b.addEventListener("click",()=>openTab(b.dataset.scrollTab)));
document.getElementById("mobileMenu").addEventListener("click",()=>document.getElementById("navigation").classList.toggle("open"));

const filterButtons=document.querySelectorAll(".filter-button"),infoCards=document.querySelectorAll(".info-card");
filterButtons.forEach(b=>b.addEventListener("click",()=>{filterButtons.forEach(x=>x.classList.remove("active"));b.classList.add("active");const f=b.dataset.filter;infoCards.forEach(c=>c.classList.toggle("hidden",f!=="todos"&&c.dataset.category!==f))}));

const mindData={tecnologia:["Tecnologia","Sensores, IoT, plataformas digitais, dados e IA podem ajudar a cidade a monitorar serviços e tomar decisões."],sustentabilidade:["Sustentabilidade","Água, energia, resíduos, áreas verdes e redução de impactos ambientais fazem parte da dimensão sustentável."],mobilidade:["Mobilidade","Transporte público, GPS, sensores, gestão de tráfego e dados podem tornar os deslocamentos mais eficientes."],agricultura:["Agricultura vertical","A produção em ambientes controlados ajuda uma cidade com pouco território a ampliar a produção local de alimentos."],sociedade:["Sociedade","Uma Smart City também precisa de inclusão, participação social, segurança, privacidade e qualidade de vida."]};
document.querySelectorAll(".mind-node").forEach(n=>n.addEventListener("click",()=>{document.querySelectorAll(".mind-node").forEach(x=>x.classList.remove("active"));n.classList.add("active");const d=mindData[n.dataset.node];document.getElementById("mindInfo").innerHTML=`<span>🧠 ${d[0].toUpperCase()}</span><h3>${d[0]}</h3><p>${d[1]}</p>`}));

const quizCards=document.querySelectorAll(".quiz-card"),correct=[true,true,true,true,false];let answers=new Array(5).fill(null);
function updateQuiz(){const a=answers.filter(x=>x!==null).length;document.getElementById("quizProgress").style.width=`${a/5*100}%`;document.getElementById("quizProgressText").textContent=`${a} / 5`;if(a<5)return;const score=answers.reduce((sum,x,i)=>sum+(x===correct[i]?1:0),0);document.getElementById("scoreText").textContent=`${score}/5`;document.getElementById("scoreMessage").textContent=score===5?"🏆 Excelente!":score>=4?"👏 Muito bom!":score>=3?"👍 Bom trabalho!":"📚 Continue estudando!"}
quizCards.forEach((c,i)=>c.querySelectorAll(".quiz-options button").forEach(b=>b.addEventListener("click",()=>{answers[i]=b.dataset.answer==="true";c.classList.add("answered");c.querySelectorAll("button").forEach(x=>x.classList.remove("selected-yes","selected-no"));b.classList.add(answers[i]?"selected-yes":"selected-no");updateQuiz()})));
document.getElementById("restartQuiz").addEventListener("click",()=>{answers=new Array(5).fill(null);quizCards.forEach(c=>{c.classList.remove("answered");c.querySelectorAll("button").forEach(b=>b.classList.remove("selected-yes","selected-no"))});document.getElementById("scoreText").textContent="0/5";document.getElementById("scoreMessage").textContent="Responda todas as perguntas para descobrir seu resultado.";updateQuiz()});
document.querySelectorAll("[data-poll]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-poll]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");const f=document.getElementById("pollFeedback");f.textContent=`✓ Voto registrado: ${b.dataset.poll}`;f.classList.add("show")}));

const searchData=[["Agricultura vertical","Produção de alimentos em pouco espaço","singapura","agricultura"],["NEWater","Gestão e reúso da água","singapura","curiosidades"],["Supertrees","Arquitetura e sustentabilidade","singapura","curiosidades"],["IoT","Sensores e Internet das Coisas","tecnologias","todos"],["Smart Grid","Energia inteligente","tecnologias","todos"],["Mobilidade","Transporte e dados","tecnologias","todos"],["Teste sua cidade","Diagnóstico de 15 perguntas","teste-cidade","todos"],["Hawker Centres","Cultura e alimentação","singapura","cultura"]];
const si=document.getElementById("searchInput"),sr=document.getElementById("searchResults");
si.addEventListener("input",()=>{const q=si.value.trim().toLowerCase();if(!q){sr.classList.remove("active");return}const r=searchData.filter(x=>(x[0]+" "+x[1]).toLowerCase().includes(q)).slice(0,7);sr.innerHTML=r.length?r.map(x=>`<div class="search-result" data-tab="${x[2]}" data-cat="${x[3]}"><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join(""):`<div class="search-result"><strong>Nenhum resultado</strong><small>Tente outro termo.</small></div>`;sr.classList.add("active");sr.querySelectorAll("[data-tab]").forEach(x=>x.addEventListener("click",()=>{openTab(x.dataset.tab);if(x.dataset.cat!=="todos"){document.querySelectorAll(".filter-button").forEach(b=>b.classList.toggle("active",b.dataset.filter===x.dataset.cat));infoCards.forEach(c=>c.classList.toggle("hidden",c.dataset.category!==x.dataset.cat))}si.value="";sr.classList.remove("active")}))});
document.addEventListener("click",e=>{if(!e.target.closest(".search-container"))sr.classList.remove("active")});

/* TESTE DE 15 PERGUNTAS DA CIDADE */
const cityQuestions=[
["Mobilidade","O transporte público da sua cidade é amplo, confiável e integrado?"],
["Mobilidade","Existem sistemas digitais ou dados usados para acompanhar e melhorar o trânsito?"],
["Ambiente","A cidade possui políticas e áreas verdes para reduzir impactos ambientais e melhorar a qualidade de vida?"],
["Resíduos","A coleta de lixo é organizada e existem iniciativas de reciclagem ou redução de resíduos?"],
["Água","A cidade monitora a qualidade da água e trabalha para reduzir perdas e desperdícios?"],
["Energia","Existem iniciativas de eficiência energética, energia renovável ou redes elétricas inteligentes?"],
["Digital","Serviços públicos importantes podem ser acessados digitalmente pela população?"],
["Dados","A administração usa dados para planejar serviços, infraestrutura ou políticas públicas?"],
["Participação","Os moradores conseguem comunicar problemas urbanos e participar de decisões públicas por canais digitais ou presenciais?"],
["Segurança","Existem tecnologias e políticas integradas para prevenção e resposta a emergências, sem ignorar privacidade?"],
["Acessibilidade","Transporte, espaços públicos e serviços são pensados para pessoas com diferentes necessidades?"],
["Planejamento","A cidade utiliza planejamento urbano de longo prazo para habitação, transporte, infraestrutura e uso do solo?"],
["Saúde e educação","A tecnologia é usada para melhorar o acesso ou a qualidade de serviços de saúde e educação?"],
["Alimentação","Existem iniciativas de agricultura urbana, produção local ou segurança alimentar?"],
["Inovação","A cidade estimula inovação, pesquisa, startups ou testes de novas soluções urbanas?"]
];
const cityContainer=document.getElementById("cityQuestions");
let cityAnswers=new Array(15).fill(null);
cityQuestions.forEach((q,i)=>{cityContainer.insertAdjacentHTML("beforeend",`<article class="city-question" data-index="${i}"><div class="question-number">${String(i+1).padStart(2,"0")}</div><span class="category">${q[0]}</span><span class="answered-label">✓ Respondida</span><h3>${q[1]}</h3><div class="city-options"><button data-answer="true">✓ Sim</button><button data-answer="false">✕ Não</button></div></article>`)});
document.querySelectorAll(".city-question").forEach((c,i)=>c.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{cityAnswers[i]=b.dataset.answer==="true";c.classList.add("answered");c.querySelectorAll("button").forEach(x=>x.classList.remove("selected-yes","selected-no"));b.classList.add(cityAnswers[i]?"selected-yes":"selected-no");updateCityDiagnosis()})));
function updateCityDiagnosis(){const answered=cityAnswers.filter(x=>x!==null).length;document.getElementById("cityTestProgress").style.width=`${answered/15*100}%`;document.getElementById("cityTestProgressText").textContent=`${answered} / 15`;if(answered<15)return;const score=cityAnswers.filter(Boolean).length;const pct=Math.round(score/15*100);const name=document.getElementById("cityName").value.trim()||"Sua cidade";let level,title,base,suggestions=[];
if(pct>=87){level="Muito avançada";title=`${name} apresenta forte perfil de cidade inteligente`;base=`Com ${score} respostas positivas em 15, ${name} demonstra muitas características associadas a uma Smart City. O perfil se aproxima de várias dimensões usadas para analisar cidades avançadas, embora isso não signifique que seja equivalente a Singapura.`}
else if(pct>=67){level="Em desenvolvimento";title=`${name} está no caminho para se tornar mais inteligente`;base=`Com ${score} respostas positivas, ${name} já apresenta uma base importante de infraestrutura, serviços e gestão inteligente. A comparação com Singapura indica que ainda existem dimensões que podem ser fortalecidas.`}
else if(pct>=47){level="Intermediária";title=`${name} possui alguns elementos inteligentes, mas há lacunas`;base=`Com ${score} respostas positivas, ${name} tem iniciativas importantes, porém ainda precisa integrar melhor tecnologia, sustentabilidade, serviços e participação da população.`}
else{level="Baixa maturidade";title=`${name} ainda tem bastante espaço para avançar`;base=`Com ${score} respostas positivas, ${name} apresenta poucas das características avaliadas. Isso não significa que seja uma cidade “ruim”: indica apenas que existem oportunidades para desenvolver infraestrutura, serviços e gestão inteligente.`}
const missing=cityAnswers.map((x,i)=>x===false?cityQuestions[i][0]+": "+cityQuestions[i][1]:null).filter(Boolean);
suggestions=missing.slice(0,5).map(x=>`<div class="suggestion">💡 <strong>Prioridade:</strong> ${x}</div>`);
document.getElementById("cityScore").textContent=`${pct}%`;document.getElementById("cityLevel").textContent=level;document.getElementById("cityResultTitle").textContent=title;document.getElementById("cityDiagnosis").textContent=base+(missing.length?` O teste identificou ${missing.length} ponto(s) para melhorar; veja algumas prioridades abaixo.`:" O teste não identificou respostas negativas. Mesmo assim, uma Smart City precisa de melhoria contínua, segurança, privacidade e inclusão.");document.getElementById("citySuggestions").innerHTML=suggestions.length?suggestions.join(""):`<div class="suggestion">🌟 <strong>Parabéns:</strong> todas as dimensões avaliadas receberam resposta positiva.</div>`}
document.getElementById("cityName").addEventListener("input",()=>{if(cityAnswers.every(x=>x!==null))updateCityDiagnosis()});
